## Example of preprocessing datasets for evaluating outlier detection algorithms

In [97]:
import time
import scipy
import numpy as np
import pandas as pd
import openml as oml

In [91]:
data = oml.datasets.get_dataset(772)
X, y = data.get_data(target=data.default_target_attribute)

In [92]:
print(X.shape)
X

(2178, 3)


array([[ 33.  , -52.26,  28.3 ],
       [ 36.  ,  45.53, 150.93],
       [ 57.  ,  41.85, 142.78],
       ...,
       [527.  ,  27.87, 139.51],
       [ 51.  ,  36.43, 140.98],
       [ 41.  ,  24.02, 122.23]], dtype=float32)

In [93]:
y.shape[0]
y

array([1, 0, 0, ..., 0, 1, 0])

In [94]:
y = y.reshape((2178,1))
y.shape

(2178, 1)

In [95]:
Xy = np.concatenate((X,y), axis=1)
Xy.shape
Xy

array([[ 33.        , -52.25999832,  28.29999924,   1.        ],
       [ 36.        ,  45.52999878, 150.92999268,   0.        ],
       [ 57.        ,  41.84999847, 142.77999878,   0.        ],
       ...,
       [527.        ,  27.87000084, 139.50999451,   0.        ],
       [ 51.        ,  36.43000031, 140.97999573,   1.        ],
       [ 41.        ,  24.02000046, 122.23000336,   0.        ]])

In [96]:
df_ori = pd.DataFrame(Xy)
df_ori.head()

0          1           2    3
0  33.0 -52.259998   28.299999  1.0
1  36.0  45.529999  150.929993  0.0
2  57.0  41.849998  142.779999  0.0
3  67.0  29.190001  141.149994  1.0
4  30.0 -21.660000  169.809998  1.0

In [90]:
df_ori.to_csv('yeast.csv', sep=',', index=False, header=False)

In [75]:
data_anomaly = np.genfromtxt('yeast' + '.csv', delimiter=',')
df_anomaly = pd.DataFrame(data_anomaly)
df_anomaly.head()

0     1     2     3    4    5     6     7    8
0  0.58  0.61  0.47  0.13  0.5  0.0  0.48  0.22  2.0
1  0.43  0.67  0.48  0.27  0.5  0.0  0.53  0.22  2.0
2  0.64  0.62  0.49  0.15  0.5  0.0  0.53  0.22  2.0
3  0.58  0.44  0.57  0.13  0.5  0.0  0.54  0.22  1.0
4  0.42  0.44  0.48  0.54  0.5  0.0  0.48  0.22  2.0

In [77]:
pd.value_counts(df_anomaly[8])

0.0    463
1.0    429
2.0    244
3.0    163
4.0     51
5.0     44
6.0     35
7.0     30
8.0     20
9.0      5
Name: 8, dtype: int64

In [78]:
# df_anomaly[8] = df_anomaly[8].map({0:1, 1:1, 2:0, 3:0, 4:0, 5:0, 6:0, 7:0, 8:0, 9:0, 10:0, 11:0,
#                                   12:0, 13:0, 14:0, 15:0, 16:0, 17:0, 18:0, 19:0, 20:0, 21:0, 22:1, 23:1,
#                                   24:1, 25:1, 26:1, 27:1, 28:1})
df_anomaly[8] = df_anomaly[8].map({0:0, 1:0, 2:0, 3:0, 4:0, 5:0, 6:0, 7:0, 8:0, 9:1})
pd.value_counts(df_anomaly[8])

0    1479
1       5
Name: 8, dtype: int64

In [79]:
df_anomaly

0     1     2     3    4    5     6     7  8
0     0.58  0.61  0.47  0.13  0.5  0.0  0.48  0.22  0
1     0.43  0.67  0.48  0.27  0.5  0.0  0.53  0.22  0
2     0.64  0.62  0.49  0.15  0.5  0.0  0.53  0.22  0
3     0.58  0.44  0.57  0.13  0.5  0.0  0.54  0.22  0
4     0.42  0.44  0.48  0.54  0.5  0.0  0.48  0.22  0
5     0.51  0.40  0.56  0.17  0.5  0.5  0.49  0.22  0
6     0.50  0.54  0.48  0.65  0.5  0.0  0.53  0.22  0
7     0.48  0.45  0.59  0.20  0.5  0.0  0.58  0.34  0
8     0.55  0.50  0.66  0.36  0.5  0.0  0.49  0.22  0
9     0.40  0.39  0.60  0.15  0.5  0.0  0.58  0.30  0
10    0.43  0.39  0.54  0.21  0.5  0.0  0.53  0.27  0
11    0.42  0.37  0.59  0.20  0.5  0.0  0.52  0.29  0
12    0.40  0.42  0.57  0.35  0.5  0.0  0.53  0.25  0
13    0.60  0.40  0.52  0.46  0.5  0.0  0.53  0.22  0
14    0.66  0.55  0.45  0.19  0.5  0.0  0.46  0.22  0
15    0.46  0.44  0.52  0.11  0.5  0.0  0.50  0.22  0
16    0.47  0.39  0.50  0.11  0.5  0.0  0.49  0.40  0
17    0.58  0.47  0.54  0.11  0.5  0.0  0.51  0.26  0
18    0.50  0.34  0.55  0.21  0.5  0.0  0.49  0.22  0
19    0.61  0.60  0.55  0.21  0.5  0.0  0.50  0.25  0
20    0.45  0.40  0.50  0.16  0.5  0.0  0.50  0.22  0
21    0.43  0.44  0.48  0.22  0.5  0.0  0.51  0.22  0
22    0.73  0.63  0.42  0.30  0.5  0.0  0.49  0.22  0
23    0.43  0.53  0.52  0.13  0.5  0.0  0.55  0.22  0
24    0.46  0.53  0.52  0.15  0.5  0.0  0.58  0.22  0
25    0.51  0.51  0.52  0.51  0.5  0.0  0.54  0.22  0
26    0.59  0.45  0.53  0.19  0.5  0.0  0.59  0.27  0
27    0.57  0.47  0.60  0.18  0.5  0.0  0.51  0.22  0
28    0.63  0.67  0.57  0.24  0.5  0.0  0.49  0.22  0
29    0.80  0.88  0.36  0.39  0.5  0.0  0.56  0.33  0
...    ...   ...   ...   ...  ...  ...   ...   ... ..
1454  0.57  0.59  0.49  0.86  0.5  0.0  0.47  0.22  0
1455  0.38  0.40  0.39  0.19  0.5  0.0  0.46  0.62  0
1456  0.77  0.74  0.37  0.29  0.5  0.0  0.45  0.22  0
1457  0.47  0.38  0.58  0.19  0.5  0.0  0.57  0.22  0
1458  0.50  0.61  0.44  0.20  0.5  0.0  0.49  0.22  0
1459  0.41  0.45  0.46  0.23  0.5  0.0  0.50  0.70  0
1460  0.46  0.62  0.46  0.54  0.5  0.0  0.51  0.27  0
1461  0.74  0.75  0.45  0.44  0.5  0.0  0.52  0.22  0
1462  0.52  0.53  0.58  0.69  0.5  0.0  0.50  0.22  0
1463  0.41  0.47  0.50  0.14  0.5  0.0  0.53  0.37  0
1464  0.25  0.40  0.52  0.15  0.5  0.0  0.56  0.28  0
1465  0.58  0.56  0.38  0.39  0.5  0.0  0.54  0.57  0
1466  0.32  0.29  0.29  0.08  0.5  0.0  0.52  0.22  0
1467  0.38  0.48  0.57  0.30  0.5  0.0  0.41  0.11  0
1468  0.39  0.58  0.47  0.18  0.5  0.0  0.48  0.22  0
1469  0.38  0.47  0.47  0.18  0.5  0.0  0.44  0.26  0
1470  0.63  0.57  0.50  0.48  0.5  0.0  0.51  0.22  0
1471  0.51  0.45  0.62  0.25  0.5  0.0  0.59  0.22  0
1472  0.59  0.67  0.54  0.19  0.5  0.0  0.48  0.60  0
1473  0.60  0.61  0.54  0.11  0.5  0.0  0.46  0.22  0
1474  0.48  0.61  0.57  0.17  0.5  0.0  0.45  0.22  0
1475  0.71  0.50  0.50  0.18  0.5  0.0  0.46  0.22  0
1476  0.61  0.48  0.54  0.25  0.5  0.0  0.50  0.22  0
1477  0.38  0.32  0.64  0.41  0.5  0.0  0.44  0.11  0
1478  0.38  0.40  0.66  0.35  0.5  0.0  0.43  0.11  0
1479  0.81  0.62  0.43  0.17  0.5  0.0  0.53  0.22  0
1480  0.47  0.43  0.61  0.40  0.5  0.0  0.48  0.47  0
1481  0.67  0.57  0.36  0.19  0.5  0.0  0.56  0.22  0
1482  0.43  0.40  0.60  0.16  0.5  0.0  0.53  0.39  0
1483  0.65  0.54  0.54  0.13  0.5  0.0  0.53  0.22  0

[1484 rows x 9 columns]

In [81]:
df_anomaly.to_csv('yeast_anomaly.csv', sep=',', index=False, header=False)